# Generated by Django 3.1.5 on 2021-05-04 08:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stockManagement', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stock',
            name='issueTo',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ven', to='stockManagement.vendor'),
        ),
        migrations.AlterField(
            model_name='stock',
            name='phone',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='phn', to='stockManagement.vendor'),
        ),
    ]
