# Generated by Django 3.1.5 on 2021-05-04 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stockManagement', '0002_auto_20210504_1447'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='lastUpdate',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='vendor',
            name='lastUpdate',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
