# Generated by Django 3.1.5 on 2021-05-05 04:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stockManagement', '0003_auto_20210504_1616'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stock',
            name='issueQuantity',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='stock',
            name='receiveQuantity',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
