# Generated by Django 3.1.5 on 2021-05-05 06:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stockManagement', '0004_auto_20210505_1036'),
    ]

    operations = [
        migrations.RenameField(
            model_name='stock',
            old_name='exportToCSV',
            new_name='ExportCSV',
        ),
    ]
